[profile.default]
src = 'contracts'
out = 'out'
libs = [
    'lib'
]
ffi=true
verbosity=5
solc_version = "0.8.20"
test = "test"
coverage = true

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
     "forge-std/=lib/forge-std/src/"
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config